In [129]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [130]:
import io

In [131]:
from google.colab import files
uploaded = files.upload()

Saving TSLA.csv to TSLA (1).csv


In [133]:
df = pd.read_csv(io.BytesIO(uploaded['TSLA (1).csv']))
print(df)

           Date       Open       High        Low      Close  Adj Close
0     6/30/2010   1.719333   2.028000   1.553333   1.588667   1.588667
1      7/1/2010   1.666667   1.728000   1.351333   1.464000   1.464000
2      7/2/2010   1.533333   1.540000   1.247333   1.280000   1.280000
3      7/6/2010   1.333333   1.333333   1.055333   1.074000   1.074000
4      7/7/2010   1.093333   1.108667   0.998667   1.053333   1.053333
...         ...        ...        ...        ...        ...        ...
2512  6/23/2020  66.592003  67.466667  66.267334  66.785332  66.785332
2513  6/24/2020  66.274002  66.725334  63.542667  64.056664  64.056664
2514  6/25/2020  63.618000  65.732002  62.476665  65.732002  65.732002
2515  6/26/2020  66.318665  66.333336  63.658001  63.982666  63.982666
2516  6/29/2020  64.600670  67.333336  63.234669  67.290001  67.290001

[2517 rows x 6 columns]


# New Section

In [134]:
df = df.drop(['Date'], axis = 1)
df.head()

Open      High       Low     Close  Adj Close
0  1.719333  2.028000  1.553333  1.588667   1.588667
1  1.666667  1.728000  1.351333  1.464000   1.464000
2  1.533333  1.540000  1.247333  1.280000   1.280000
3  1.333333  1.333333  1.055333  1.074000   1.074000
4  1.093333  1.108667  0.998667  1.053333   1.053333

In [135]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
y = y.astype('int')

In [136]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [137]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [138]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [139]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [140]:
y_pred = classifier.predict(x_test)

In [141]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[80  0  0 ...  0  0  0]
 [54  0  0 ...  0  0  0]
 [ 6  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


0.3948412698412698

In [142]:
y_pred

array([12, 16,  1, 14, 16, 16, 12, 17, 13, 12,  1, 14,  1,  1,  1,  1, 20,
        1, 20, 14, 16, 23, 16, 14,  1,  2,  1,  1, 16, 16, 14, 23,  1, 20,
       14, 15,  1, 16,  1, 13,  1,  1, 16, 13, 16, 23, 13,  1, 12, 14, 23,
       16, 16, 13, 20,  1, 12, 23, 17,  1, 23, 13, 23, 14,  1, 20, 20,  1,
       14, 13, 14, 14, 17,  1, 13, 20, 23, 14, 16,  1, 14, 12,  1, 23, 14,
        1,  1,  1,  1, 17, 16, 23, 17, 16, 14, 23, 16,  1, 23,  1, 20, 20,
        2, 17, 16, 16,  1,  1,  1, 14,  1, 20, 23,  1,  1, 16, 23, 16, 20,
       15, 23, 13, 20,  1, 16, 20, 14,  1,  1, 16,  1, 12, 20,  2,  1, 20,
       17,  1,  1, 23, 16, 23, 16, 15, 13,  1, 14, 17,  1, 16, 13, 14, 14,
       14, 12, 13,  1, 16, 16, 16, 16,  1,  1,  1, 13, 15, 16,  1,  1, 23,
       23,  1, 12, 14, 14,  1, 20, 20, 14,  1,  1, 20, 20, 16,  1,  1,  1,
        1, 14, 16, 16, 15,  1, 14,  1, 13,  1, 16, 13, 14, 16, 17, 16, 16,
        2, 12, 16, 16, 23,  1,  1,  1, 16, 20, 13, 17,  1, 14, 16, 16, 14,
       16, 16, 14,  1, 13

In [143]:
y_test

array([10, 17,  1, 14, 16, 16, 10, 20, 12, 12,  1, 15,  1,  2,  2,  1, 23,
        2, 21, 15, 17, 25, 19, 14,  2,  9,  1,  2, 15, 17, 13, 53,  1, 20,
       14, 15,  1, 15,  2, 13,  1,  1, 16, 13, 17, 68, 13,  1, 11, 14, 25,
       15, 16, 13, 21,  1, 11, 24, 20,  2, 51, 12, 57, 13,  1, 23, 23,  3,
       14, 13, 13, 14, 19,  1, 13, 21, 53, 14, 18,  1, 14, 12,  2, 52, 14,
        2,  1,  2,  2, 20, 15, 24, 19, 18, 14, 60, 15,  1, 30,  3, 23, 21,
        8, 19, 15, 16,  2,  1,  2, 14,  1, 20, 25,  2,  2, 16, 66, 15, 23,
       15, 24, 13, 22,  1, 15, 21, 14,  2,  1, 16,  2, 12, 20, 10,  1, 21,
       20,  2,  1, 28, 17, 59, 15, 15, 12,  2, 14, 19,  1, 19, 13, 14, 14,
       15, 11, 13,  1, 16, 18, 18, 19,  2,  2,  1, 13, 15, 17,  1,  2, 49,
       37,  1, 10, 14, 14,  2, 23, 23, 13,  3,  2, 22, 23, 16,  2,  1,  2,
        5, 13, 15, 17, 15,  1, 14,  1, 13,  1, 18, 13, 14, 19, 20, 18, 18,
        9, 12, 16, 16, 27,  2,  1,  1, 17, 22, 13, 20,  2, 14, 16, 16, 14,
       16, 16, 13,  6, 13