In [58]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [59]:
import io

In [60]:
from google.colab import files
uploaded = files.upload()

Saving HD.csv to HD.csv


In [64]:
df = pd.read_csv(io.BytesIO(uploaded['HD.csv']))
print(df)

           Date        Open        High         Low       Close   Adj Close  \
0      1/4/2010   29.150000   29.150000   28.549999   28.670000   20.551073   
1      1/5/2010   28.730000   28.990000   28.290001   28.879999   20.701614   
2      1/6/2010   28.879999   29.000000   28.700001   28.780001   20.629927   
3      1/7/2010   28.860001   29.219999   28.730000   29.120001   20.873646   
4      1/8/2010   29.000000   29.240000   28.690001   28.980000   20.773291   
...         ...         ...         ...         ...         ...         ...   
2635  6/23/2020  253.000000  253.440002  250.130005  250.309998  230.219467   
2636  6/24/2020  247.809998  250.289993  242.729996  246.130005  226.374954   
2637  6/25/2020  244.800003  246.350006  242.199997  245.380005  225.685181   
2638  6/26/2020  245.350006  246.100006  240.250000  241.009995  221.665909   
2639  6/29/2020  242.660004  246.500000  240.339996  246.119995  226.365753   

         Average  
0      27.214214  
1      27.118

# New Section

In [65]:
df = df.drop(['Date'], axis = 1)
df.head()

Open       High        Low      Close  Adj Close    Average
0  29.150000  29.150000  28.549999  28.670000  20.551073  27.214214
1  28.730000  28.990000  28.290001  28.879999  20.701614  27.118323
2  28.879999  29.000000  28.700001  28.780001  20.629927  27.197986
3  28.860001  29.219999  28.730000  29.120001  20.873646  27.360729
4  29.000000  29.240000  28.690001  28.980000  20.773291  27.336658

In [66]:
x = df.iloc[:, 0:5].values
y = df.iloc[:, 5].values
y = y.astype('int')

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [68]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [69]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [70]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [71]:
y_pred = classifier.predict(x_test)

In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.026515151515151516

In [73]:
y_pred

array([ 76, 110,  35,  35, 130, 195, 195,  35, 130, 195, 195, 195, 195,
        35,  35, 130, 195,  35, 195,  35,  35, 195,  35,  35,  35, 195,
       195,  35,  35,  35,  35, 195,  35,  35, 195,  35,  35,  35, 195,
       195, 110,  35, 195, 195, 195, 195,  35, 195, 195,  35,  35, 195,
       195, 130,  35,  35,  35,  35, 195, 195, 195, 195,  35,  35, 195,
        35,  35, 110,  35,  35,  35,  35,  35, 195, 195, 195, 195, 195,
       130,  35, 195,  35, 195, 195,  35, 195, 195,  35, 195, 195,  35,
       195,  35,  35,  35,  35, 195, 195, 195,  35, 195, 195,  35,  35,
        76, 195, 195, 195, 195,  35,  35, 130,  76,  35, 195,  35, 195,
       195, 142,  76, 195,  35,  76, 195, 195, 195,  35, 195,  35,  35,
        35, 195, 195, 195,  35,  35,  35, 195, 130, 195, 130,  76, 195,
        35,  35, 195, 195,  35, 195,  35,  35,  35,  35,  35,  35, 195,
        35, 195, 195, 195,  35, 195, 195,  76,  35,  35, 195, 195,  35,
       195,  35, 195, 195, 195,  35,  35,  35,  35,  35,  35,  3

In [74]:
y_test

array([103, 109,  66,  76, 110, 194, 174,  56, 110, 185, 150, 240, 142,
        72,  75, 115, 130,  38, 187,  75,  47, 175,  34,  88,  30, 130,
       229,  32,  63,  37,  33, 181,  47,  29, 130,  47,  29,  75, 131,
       221, 109,  77, 199, 125, 184, 201,  48, 171, 130,  29,  33, 131,
       169, 117,  49,  78,  30,  54, 180, 130, 192, 160,  60,  58, 182,
        57,  72, 109,  92,  88,  63,  72,  74, 173, 177, 223, 187, 214,
       111,  33, 206,  27, 130, 213,  74, 131, 193,  59, 251, 127,  33,
       148,  32,  28,  34,  49, 228, 195, 131,  80, 229, 195,  73,  29,
       101, 188, 129, 213, 213,  31,  34, 110, 106,  54, 169,  35, 223,
       128, 121, 108, 180,  26, 106, 179, 203, 206,  72, 215,  28,  77,
        35, 158, 182, 179,  31,  33,  77, 143, 118, 127, 119, 101, 125,
        76,  78, 126, 122,  49, 130,  77,  71,  54,  46,  29,  29, 173,
        57, 170, 200, 209,  77, 175, 220, 107,  35,  44, 236, 143,  75,
       228,  88, 152, 122, 177,  61,  39,  89,  34,  26,  77,  5