In [86]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [87]:
import io

In [88]:
from google.colab import files
uploaded = files.upload()

Saving CELH.csv to CELH.csv


In [89]:
df = pd.read_csv(io.BytesIO(uploaded['CELH.csv']))
print(df)

          Date       Open       High        Low      Close  Adj Close
0     2/8/2023  32.756668  33.290001  32.296665  32.470001  32.470001
1     2/9/2023  32.973331  33.526669  31.889999  32.136665  32.136665
2    2/10/2023  31.826668  32.743332  31.173332  32.376667  32.376667
3    2/13/2023  32.623333  33.099998  31.723333  32.619999  32.619999
4    2/14/2023  32.176666  33.029999  31.870001  32.060001  32.060001
..         ...        ...        ...        ...        ...        ...
246   2/1/2024  50.000000  51.770000  49.560001  51.099998  51.099998
247   2/2/2024  51.570000  53.790001  50.900002  53.349998  53.349998
248   2/5/2024  52.540001  53.230000  50.290001  53.209999  53.209999
249   2/6/2024  53.169998  56.709999  53.049999  55.799999  55.799999
250   2/7/2024  55.799999  57.869999  55.380001  57.770000  57.770000

[251 rows x 6 columns]


# New Section

In [90]:
df = df.drop(['Date'], axis = 1)
df.head()

Open       High        Low      Close  Adj Close
0  32.756668  33.290001  32.296665  32.470001  32.470001
1  32.973331  33.526669  31.889999  32.136665  32.136665
2  31.826668  32.743332  31.173332  32.376667  32.376667
3  32.623333  33.099998  31.723333  32.619999  32.619999
4  32.176666  33.029999  31.870001  32.060001  32.060001

In [91]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
y = y.astype('int')

In [92]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [93]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [94]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [95]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [96]:
y_pred = classifier.predict(x_test)

In [97]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 

0.3333333333333333

In [98]:
y_pred

array([59, 49, 49, 55, 59, 59, 59, 49, 43, 59, 55, 59, 50, 59, 49, 43, 49,
       50, 57, 49, 55, 29, 52, 49, 52, 49, 29, 29, 49, 29, 52, 44, 49, 59,
       52, 59, 50, 29, 29, 57, 49, 29, 50, 49, 49, 49, 52, 29, 43, 52, 43])

In [ ]:
y_test