In [113]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [114]:
import io

In [117]:
from google.colab import files
uploaded = files.upload()

Saving HD.csv to HD (2).csv


In [118]:
df = pd.read_csv(io.BytesIO(uploaded['HD (2).csv']))
print(df)

           Date        Open        High         Low       Close   Adj Close
0      1/4/2010   29.150000   29.150000   28.549999   28.670000   20.551073
1      1/5/2010   28.730000   28.990000   28.290001   28.879999   20.701614
2      1/6/2010   28.879999   29.000000   28.700001   28.780001   20.629927
3      1/7/2010   28.860001   29.219999   28.730000   29.120001   20.873646
4      1/8/2010   29.000000   29.240000   28.690001   28.980000   20.773291
...         ...         ...         ...         ...         ...         ...
2635  6/23/2020  253.000000  253.440002  250.130005  250.309998  230.219467
2636  6/24/2020  247.809998  250.289993  242.729996  246.130005  226.374954
2637  6/25/2020  244.800003  246.350006  242.199997  245.380005  225.685181
2638  6/26/2020  245.350006  246.100006  240.250000  241.009995  221.665909
2639  6/29/2020  242.660004  246.500000  240.339996  246.119995  226.365753

[2640 rows x 6 columns]


# New Section

In [119]:
df = df.drop(['Date'], axis = 1)
df.head()

Open       High        Low      Close  Adj Close
0  29.150000  29.150000  28.549999  28.670000  20.551073
1  28.730000  28.990000  28.290001  28.879999  20.701614
2  28.879999  29.000000  28.700001  28.780001  20.629927
3  28.860001  29.219999  28.730000  29.120001  20.873646
4  29.000000  29.240000  28.690001  28.980000  20.773291

In [120]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
y = y.astype('int')

In [121]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [123]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [124]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [125]:
y_pred = classifier.predict(x_test)

In [126]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.0928030303030303

In [127]:
y_pred

array([ 62,  92,  27,  62, 108, 170, 170,  27,  92, 170, 131, 170, 131,
        62,  62, 108, 114,  27, 170,  62,  27, 170,  27,  62,  27, 114,
       170,  27,  27,  27,  27, 170,  27,  27, 114,  27,  27,  62, 114,
       170,  92,  62, 170, 109, 170, 170,  27, 170, 114,  27,  27, 114,
       170, 108,  27,  62,  27,  27, 170, 114, 170, 131,  27,  27, 170,
        27,  62,  92,  62,  62,  27,  62,  62, 170, 170, 170, 170, 170,
       108,  27, 170,  27, 114, 170,  62, 114, 170,  27, 170, 109,  27,
       131,  27,  27,  27,  27, 170, 170, 114,  62, 170, 170,  62,  27,
        62, 170, 114, 170, 170,  27,  27,  94,  62,  27, 170,  27, 170,
       109, 108,  62, 170,  27,  62, 170, 170, 170,  62, 170,  27,  62,
        27, 131, 170, 170,  27,  27,  62, 131, 108, 109, 108,  62, 109,
        62,  62, 109, 108,  27, 114,  62,  62,  27,  27,  27,  27, 170,
        27, 170, 170, 170,  62, 170, 170,  62,  27,  27, 170, 131,  62,
       170,  62, 131, 109, 170,  27,  27,  62,  27,  27,  62,  2

In [128]:
y_test

array([ 87,  92,  54,  63,  94, 177, 157,  46,  93, 167, 131, 226, 125,
        59,  61,  98, 112,  30, 178,  61,  38, 156,  27,  74,  23, 113,
       211,  26,  51,  29,  25, 161,  38,  22, 112,  38,  22,  62, 114,
       202,  92,  64, 186, 110, 165, 185,  39, 155, 112,  22,  27, 114,
       153, 100,  40,  65,  23,  43, 160, 111, 172, 142,  49,  47, 162,
        46,  60,  93,  77,  73,  51,  58,  61, 157, 158, 205, 168, 197,
        94,  26, 189,  22, 112, 195,  61, 114, 175,  48, 234, 109,  26,
       130,  25,  21,  27,  39, 211, 175, 113,  67, 210, 174,  60,  23,
        85, 172, 111, 195, 197,  24,  27,  94,  90,  43, 152,  27, 207,
       109, 104,  91, 163,  20,  90, 159, 182, 190,  60, 199,  22,  64,
        27, 141, 166, 160,  24,  26,  64, 126, 101, 110, 101,  86, 109,
        63,  64, 109, 104,  40, 113,  64,  58,  44,  37,  23,  22, 154,
        46, 152, 180, 190,  63, 163, 200,  91,  28,  35, 219, 124,  63,
       212,  74, 132, 105, 161,  50,  31,  75,  27,  20,  64,  4