In [15]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [16]:
import io

In [17]:
from google.colab import files
uploaded = files.upload()

Saving WYY.csv to WYY.csv


In [19]:
df = pd.read_csv(io.BytesIO(uploaded['WYY.csv']))
print(df)

           Date  Open  High   Low  Close  Adj Close  Volume
0    2023-02-08  2.07  2.07  1.97   1.97       1.97  118800
1    2023-02-09  1.97  2.07  1.94   1.94       1.94  126200
2    2023-02-10  2.01  2.13  1.95   2.02       2.02   42800
3    2023-02-13  2.02  2.15  2.02   2.10       2.10   13300
4    2023-02-14  2.03  2.09  2.03   2.07       2.07   19300
..          ...   ...   ...   ...    ...        ...     ...
246  2024-02-01  3.23  3.25  3.14   3.22       3.22   44800
247  2024-02-02  3.23  3.25  2.94   2.98       2.98   60100
248  2024-02-05  2.95  2.95  2.80   2.85       2.85   97300
249  2024-02-06  2.85  2.88  2.71   2.87       2.87   17700
250  2024-02-07  2.86  2.92  2.72   2.77       2.77   15700

[251 rows x 7 columns]


# New Section

In [20]:
df = df.drop(['Date'], axis = 1)
df.head()

Open  High   Low  Close  Adj Close  Volume
0  2.07  2.07  1.97   1.97       1.97  118800
1  1.97  2.07  1.94   1.94       1.94  126200
2  2.01  2.13  1.95   2.02       2.02   42800
3  2.02  2.15  2.02   2.10       2.10   13300
4  2.03  2.09  2.03   2.07       2.07   19300

In [21]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
y = y.astype('int')

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [28]:
y_pred = classifier.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[43  0  0]
 [ 1  6  0]
 [ 0  0  1]]


0.9803921568627451

In [30]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

In [31]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1])