In [75]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [76]:
import io

In [77]:
from google.colab import files
uploaded = files.upload()

Saving ERIE.csv to ERIE.csv


In [78]:
df = pd.read_csv(io.BytesIO(uploaded['ERIE.csv']))
print(df)

           Date        Open        High         Low       Close   Adj Close  \
0      1/4/2010   39.150002   39.560001   39.150002   39.349998   25.904909   
1      1/5/2010   39.540001   39.540001   38.540001   38.770000   25.523081   
2      1/6/2010   38.669998   38.790001   38.410000   38.779999   25.529673   
3      1/7/2010   38.540001   38.959999   38.500000   38.930000   25.628424   
4      1/8/2010   38.799999   38.980000   38.529999   38.810001   25.549421   
...         ...         ...         ...         ...         ...         ...   
2635  6/23/2020  184.309998  187.639999  183.720001  186.110001  171.158691   
2636  6/24/2020  186.350006  186.350006  182.009995  183.410004  168.675598   
2637  6/25/2020  183.289993  188.869995  181.199997  188.169998  173.053253   
2638  6/26/2020  187.380005  188.880005  184.899994  186.059998  171.112732   
2639  6/29/2020  187.619995  190.580002  187.520004  188.500000  173.356689   

         Average  
0      36.622982  
1      36.382

# New Section

In [79]:
df = df.drop(['Date'], axis = 1)
df.head()

Open       High        Low      Close  Adj Close    Average
0  39.150002  39.560001  39.150002  39.349998  25.904909  36.622982
1  39.540001  39.540001  38.540001  38.770000  25.523081  36.382617
2  38.669998  38.790001  38.410000  38.779999  25.529673  36.035934
3  38.540001  38.959999  38.500000  38.930000  25.628424  36.111685
4  38.799999  38.980000  38.529999  38.810001  25.549421  36.133884

In [80]:
x = df.iloc[:, 0:5].values
y = df.iloc[:, 5].values
y = y.astype('int')

In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [83]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [84]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [85]:
y_pred = classifier.predict(x_test)

In [86]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.07765151515151515

In [87]:
y_pred

array([ 67,  67,  66,  66,  67, 181, 115,  66,  67, 115, 115, 115, 115,
        66,  67,  72,  72,  66, 115,  66,  66, 115,  66,  66,  66, 115,
       115,  66,  66,  66,  66, 115,  66,  66, 115,  66,  66,  66, 115,
       181,  67,  66, 115, 115, 115, 181,  66, 115,  94,  66,  66, 115,
       115,  67,  66,  66,  66,  66, 115,  72, 115, 115,  66,  66, 115,
        66,  66,  72,  67,  66,  66,  66,  66, 115, 115, 181, 115, 181,
        67,  66, 181,  66,  94, 181,  66, 115, 115,  66, 115,  72,  66,
       115,  66,  66,  66,  66, 115, 115,  72,  66, 181, 115,  66,  66,
        67, 181,  72, 181, 115,  66,  66,  67,  67,  66, 115,  66, 115,
        72,  72,  67, 115,  66,  67, 115, 115, 181,  66, 181,  66,  66,
        66, 115, 115, 115,  66,  66,  66, 115,  72,  72,  67,  72, 115,
        66,  66,  72,  72,  66, 115,  66,  66,  66,  66,  66,  66, 115,
        66, 115, 115, 181,  66, 115, 181,  67,  66,  66, 115, 115,  66,
       115,  66, 115,  72, 115,  66,  66,  66,  66,  66,  66,  6

In [88]:
y_test

array([ 79,  80,  70,  66,  82, 232, 122,  60,  80, 111, 112, 170, 116,
        67,  77,  88,  88,  71, 153,  76,  73, 117,  73,  73,  38,  96,
       166,  69,  65,  68,  43, 111,  72,  57,  99,  72,  58,  66, 108,
       189,  79,  66, 176, 103, 110, 247,  70, 131,  94,  43,  69,  95,
       127,  80,  64,  70,  52,  59, 115,  88, 115, 115,  66,  60, 115,
        60,  73,  91,  81,  73,  69,  71,  67, 131, 122, 212, 118, 217,
        82,  61, 217,  64,  93, 228,  66, 109, 165,  66, 182,  92,  71,
       121,  64,  36,  64,  70, 167, 115,  92,  72, 202, 122,  67,  56,
        84, 198,  89, 214, 169,  68,  63,  81,  77,  59, 127,  67, 165,
        93,  92,  78, 177,  46,  78, 112, 123, 258,  70, 206,  52,  73,
        67, 126, 179, 111,  67,  59,  70, 119,  89,  89,  85,  86, 102,
        65,  68,  89,  92,  63, 109,  70,  71,  60,  66,  52,  52, 116,
        61, 115, 123, 217,  68, 158, 211,  80,  65,  70, 158, 117,  70,
       163,  74, 110,  88, 141,  65,  72,  75,  65,  35,  71,  6