In [32]:
#Linear Discriminant Analysis for dimensionality reduction
#Dataset preparation
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [33]:
import io

In [34]:
from google.colab import files
uploaded = files.upload()

Saving TSM.csv to TSM.csv


In [35]:
df = pd.read_csv(io.BytesIO(uploaded['TSM.csv']))
print(df)

           Date        Open        High         Low       Close   Adj Close  \
0    2023-02-08   95.019997   95.940002   94.230003   94.279999   92.482452   
1    2023-02-09   96.000000   98.570000   95.620003   96.690002   94.846504   
2    2023-02-10   95.949997   96.500000   94.250000   95.370003   93.551674   
3    2023-02-13   95.470001   96.389999   94.910004   96.110001   94.277557   
4    2023-02-14   95.820000   98.989998   95.220001   97.959999   96.092293   
..          ...         ...         ...         ...         ...         ...   
246  2024-02-01  113.800003  114.029999  112.610001  113.389999  113.389999   
247  2024-02-02  114.860001  115.959999  113.919998  115.750000  115.750000   
248  2024-02-05  117.129997  119.540001  116.580002  118.790001  118.790001   
249  2024-02-06  120.120003  120.989998  118.279999  119.379997  119.379997   
250  2024-02-07  120.010002  125.000000  120.000000  124.980003  124.980003   

       Volume  
0    12899700  
1    16997400  
2  

# New Section

In [36]:
df = df.drop(['Date'], axis = 1)
df.head()

Open       High        Low      Close  Adj Close    Volume
0  95.019997  95.940002  94.230003  94.279999  92.482452  12899700
1  96.000000  98.570000  95.620003  96.690002  94.846504  16997400
2  95.949997  96.500000  94.250000  95.370003  93.551674  11511400
3  95.470001  96.389999  94.910004  96.110001  94.277557   7803500
4  95.820000  98.989998  95.220001  97.959999  96.092293  15345100

In [37]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
y = y.astype('int')

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [40]:
from  sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)

In [41]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [42]:
y_pred = classifier.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

0.37254901960784315

In [44]:
y_pred

array([ 88,  96, 101,  85,  91,  86,  88,  99,  85,  91,  85,  99, 102,
        91,  99,  88,  96,  99,  91,  99,  85,  86, 116,  96,  98, 102,
        86,  85, 116,  91,  98, 101, 101, 101,  96,  91,  88,  91,  86,
        96,  99,  86, 104, 101, 102,  99,  97,  86,  85,  86,  91])

In [31]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1])